Loging/Loging/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('student/', include('students.urls', namespace='students')),
    path('faculty/', include('faculty.urls', namespace='faculty')),
]

Loging/students/urls.py
from django.urls import path, include
from .views import student_id, download
from django.conf import settings
from django.conf.urls.static import static

app_name = 'students'

urlpatterns = [
                  path('<int:students_id>/', student_id, name='students'),
                  path('download/<int:students_id>/', download, name='download')
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Loging/students/models.py
from django.db import models
from django.urls import reverse

from authorization.models import LoginStudents
# from datetime import datetime
from Group.models import GroupUniversity, Discip


class Students(models.Model):
    GroupStudents = models.ForeignKey(GroupUniversity, on_delete=models.SET_NULL, null=True,
                                      verbose_name='Студент группы')
    Last_name = models.CharField(max_length=255, verbose_name='Фамилия студента')
    First_name = models.CharField(max_length=255, verbose_name='Имя студента')
    Middle_name = models.CharField(max_length=255, verbose_name='Отчество студента')
    EmailStudents = models.EmailField(max_length=255, verbose_name='Почта студента', blank=True, null=True)
    StudentLoginPasswords = models.ForeignKey(LoginStudents, on_delete=models.CASCADE,
                                              verbose_name='Авторизация Студента', blank=True, null=True)

    def __str__(self) -> str:
        return str(f'{self.Last_name} {self.First_name} {self.Middle_name}')

    def get_absolute_url(self):
        return reverse('students', kwargs={'students_id': self.id})

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студентов'
        db_table = 'Студенты'


def upload_course_to(instance, filename):
    return filename


class Work(models.Model):
    Types_work = models.CharField(null=True)
    Course = models.CharField(null=True)
    Name_themes = models.CharField(null=True)
    Files = models.FileField(upload_to=upload_course_to, verbose_name='Работы', blank=True, null=True)
    statuc = models.BooleanField(default=False)
    DiscipId = models.ForeignKey(Discip, on_delete=models.CASCADE)
    StudentId = models.ForeignKey(Students, on_delete=models.CASCADE)

    def __str__(self):
        return self.Name_themes

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'
        db_table = 'Темы'

Loging/students/forms.py
from django.forms import forms


class FileSaveCourse(forms.Form):
    File_Course = forms.FileField()


class FileSavePractice(forms.Form):
    File_Practice = forms.FileField()


class FileSaveWCR(forms.Form):
    File_WKR = forms.FileField()

Loging/students/views.py
import os
from django.shortcuts import render, get_object_or_404, redirect, reverse, HttpResponse
from .forms import FileSaveCourse, FileSavePractice, FileSaveWCR
from .models import Students
from django.conf import settings
from django.http import HttpResponse, Http404


def student_id(request, students_id):
    from datetime import date
    studentID = get_object_or_404(Students, pk=students_id)
    students = Students.objects.filter(id=students_id)
    # course_id = ThemeStudents.objects.filter(Students_Themes=studentID).order_by('Semester', 'Status_themes')
    course = FileSaveCourse()
    practice = FileSavePractice()
    WKR = FileSaveWCR()

    if request.method == "POST":
        file_courses = FileSaveCourse(request.POST, request.FILES)
        file_practice = FileSavePractice(request.POST, request.FILES)
        file_WKR = FileSaveWCR(request.POST, request.FILES)
        date_today = date.today()
        emsil_student = request.POST.get('email_st')
        # if file_courses.is_valid():
        #     course_file = file_courses.cleaned_data['File_Course']
        #     course_semester = request.POST.get('course_sem')
        #     group_course, semester = course_semester.split('_')
        #     name_group, code_group = group_course.split('-')
        #     int_semesmter = int(semester)
        #     int_course = int(code_group[0])
        #     themes_to_update = ThemeStudents.objects.filter(
        #         Students_Themes=studentID,
        #         Semester=int_course,
        #         Status_themes=int_semesmter
        #     )
        #     if themes_to_update.exists():
        #         for themes in themes_to_update:
        #             themes.Delivery_dates = date_today
        #             themes.Course = course_file
        #             themes.save()
        #             return redirect(reverse('students:students', kwargs={'students_id': students_id}))
        #     elif not themes_to_update.exists():
        #         course_themes = ThemeStudents.objects.create(
        #             Semester=int_course,
        #             Status_themes=int_semesmter,
        #             Students_Themes=studentID,
        #             Delivery_dates=date_today,
        #             Course=course_file)
        #         course_themes.save()
        #         return redirect(reverse('students:students', kwargs={'students_id': students_id}))
        # elif file_practice.is_valid():
        #     file_practices = file_practice.cleaned_data['File_Practice']
        #     practice_semester = request.POST.get('practice_sem')
        #     group_course, semester = practice_semester.split('_')
        #     name_group, code_group = group_course.split('-')
        #     int_semesmter = int(semester)
        #     int_course = int(code_group[0])
        #     themes_to_update = ThemeStudents.objects.filter(
        #         Students_Themes=studentID,
        #         Semester=int_course,
        #         Status_themes=int_semesmter
        #     )
        #     if themes_to_update.exists():
        #         for themes in themes_to_update:
        #             themes.Delivery_dates = date_today
        #             themes.Course = file_practices
        #             themes.save()
        #     elif not themes_to_update.exists():
        #         practice_themes = ThemeStudents.objects.create(
        #             Semester=int_course,
        #             Status_themes=int_semesmter,
        #             Students_Themes=studentID,
        #             Delivery_dates=date_today,
        #             Course=file_practices)
        #         practice_themes.save()
        #         return redirect(reverse('students:students', kwargs={'students_id': students_id}))
        # elif file_WKR.is_valid():
        #     file_WKRs = file_WKR.cleaned_data['File_WKR']
        #     wkr_semester = request.POST.get('wkr_sem')
        #     group_course, semester = wkr_semester.split('_')
        #     name_group, code_group = group_course.split('-')
        #     int_semesmter = int(semester)
        #     int_course = int(code_group[0])
        #     themes_to_update = ThemeStudents.objects.filter(
        #         Students_Themes=studentID,
        #         Semester=int_course,
        #         Status_themes=int_semesmter
        #     )
        #     if themes_to_update.exists():
        #         for themes in themes_to_update:
        #             themes.Delivery_dates = date_today
        #             themes.Course = file_WKRs
        #             themes.save()
        #     elif not themes_to_update.exists():
        #         wkr_themes = ThemeStudents.objects.create(
        #             Semester=int_course,
        #             Status_themes=int_semesmter,
        #             Students_Themes=studentID,
        #             Delivery_dates=date_today,
        #             Course=file_WKRs)
        #         wkr_themes.save()
        #         return redirect(reverse('students:students', kwargs={'students_id': students_id}))
        # elif emsil_student:
        #     email_update = Students.objects.get(pk=students_id)
        #     email_update.EmailStudents = emsil_student
        #     email_update.save()
        #     return redirect(reverse('students:students', kwargs={'students_id': students_id}))
    date = {
        'id': students_id,
        'student': studentID,
        'students': students,
        # 'themes': course_id,
        'Course': course,
        'Practice': practice,
        'WKR': WKR
    }
    return render(request, 'students/indexStudent.html', context=date)


def download(request, students_id):
    # Починить скачивание архива rar
    if request.method == 'POST':
        cr = request.POST.get('course')
        file_extension = os.path.splitext(cr)[1].lower()
        if file_extension == '.zip':
            content_type = 'application/zip'
        elif file_extension == '.rar':
            content_type = 'application/x-rar-compressed'
        else:
            content_type = 'application/octet-stream'

        file_path = os.path.join(settings.MEDIA_ROOT, cr)
        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type=content_type)
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                return response
        raise Http404

Loging/students/templates/students/indexStudent.html
{% extends 'students/layoutStudent.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/tab.css' %}">
<link rel="stylesheet" href="{% static 'css/content.css' %}">
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

{% endblock %}

{% block navbar %}
<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Профиль</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <button class="btn btn-outline-success">Logout
                        <!--                        <img class="icons" src="{% static 'Icons/users.ico' %}">-->
                    </button>
                </form>
            </div>
        </div>
    </nav>
</div>
{% endblock %}

{% block content %}
{{ student.GroupStudents }}
{% if student.EmailStudents == None %}
<h5>Введите почту</h5>
<form action="{{ student.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <input type="email" name="email_st">
    <button type="submit">Сохранить почту</button>
</form>
{% else %}
{{ student.EmailStudents }}
{% endif %}
{{ student.get_Status_Students_display }}
<h3>{{ student.Last_name }} {{ student.First_name }} {{ student.Middle_name }}</h3>
<div>
<!--    {% for st in students %}-->
<!--    {% if '4' in student.GroupStudents.NameGroup %}-->
<!--    <form action="{{ student.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}-->
<!--        <div class="Course">-->
<!--            <h4>Курсовая:</h4>-->
<!--            {{ Course.File_Course }}-->
<!--            <button type="submit" name="course_sem" value="{{ student.GroupStudents }}_1">Сохранить</button>-->
<!--        </div>-->
<!--    </form>-->
<!--    <form action="{{ student.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}-->
<!--        <div class="Practic">-->
<!--            <h4>Практика:</h4>-->
<!--            {{ Practice.File_Practice }}-->
<!--            <button type="submit" name="practice_sem" value="{{ student.GroupStudents }}_2">Сохранить</button>-->
<!--        </div>-->
<!--    </form>-->
<!--    <form action="{{ student.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}-->
<!--        <div class="Practic">-->
<!--            <h4>ВКР:</h4>-->
<!--            {{ WKR.File_WKR }}-->
<!--            <button type="submit" name="wkr_sem" value="{{ student.GroupStudents }}_3">Сохранить</button>-->
<!--        </div>-->
<!--    </form>-->
<!--    {% else %}-->
<!--    <form action="{{ student.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}-->
<!--        <div class="Course">-->
<!--            <h4>Курсовая:</h4>-->
<!--            {{ Course.File_Course }}-->
<!--            <button type="submit" name="course_sem" value="{{ student.GroupStudents }}_1">Сохранить</button>-->
<!--        </div>-->
<!--    </form>-->
<!--    <form action="{{ student.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}-->
<!--        <div class="Practic">-->
<!--            <h4>Практика:</h4>-->
<!--            {{ Practice.File_Practice }}-->
<!--            <button type="submit" name="practice_sem" value="{{ student.GroupStudents }}_2">Сохранить</button>-->
<!--        </div>-->
<!--    </form>-->
<!--    {% endif %}-->
<!--    {% endfor %}-->

<h4>Все работы</h4>
<table>
    <thead>
    <tr>
        <th>
            Куср
        </th>
        <th>
            Тип работы
        </th>
        <th>
            Тема курсовой
        </th>
        <th>
            Файл
        </th>
    </tr>
    </thead>
    <tbody>{% for themes in themes %}
    <tr>
        <td>
            {{ themes.Semester }}
        </td>
        <td>
            {{ themes.get_Status_themes_display }}
        </td>
        <td>
            {% if themes.get_Status_themes_display == "Практика" %}

            {% elif themes.get_Status_themes_display == "Курсовая" %}
            {{ themes.Name_themes }}
            {% endif %}
        </td>
        <td>
            <form action="{% url 'students:download' id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <button type="submit" name="course" value="{{ themes.Course }}">{{ themes.Course }}</button>
            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<!--<input type="radio">-->

<!--<a href="#" download="{{ student.Themes.Semester_Course.Course }}">-->
<!--{{ student.Themes.Semester_Course.Course }}</a>-->
<!--<a href="#" download="{{ student.Themes.Semester_Course.Practice }}">-->
<!--{{ student.Themes.Semester_Practice.Practice }}</a>-->


{% endblock %}

{% block JS %}
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
        crossorigin="anonymous"></script>
<!--<script src="{% static 'JS/Course.js' %}"></script>-->
<script src="{% static 'JS/files_load.js' %}"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
{% endblock %}

Loging/students/templates/students/layoutStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block navbar %}
{% endblock %}

{% block content %}
{% endblock %}

{% block JS %}
{% endblock %}
</body>
</html>