Loging/Loging/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('student/', include('students.urls', namespace='students')),
    path('faculty/', include('faculty.urls', namespace='faculty')),
]

Loging/faculty/urls.py
from django.urls import path
from .views import faculty_index, logoutUser, Parsing, archive, Report, download_file, graph, Working, faculty_students, \
    transfer
# from .views import faculty_index, logoutUser, Parsing, faculty_students, download_file, transfer, graph
from django.conf import settings
from django.conf.urls.static import static

app_name = 'faculty'

urlpatterns = [
                  path('<int:faculty_id>', faculty_index, name='faculty_index'),
                  path('archive/<int:faculty_id>/', archive, name='archive'),
                  path('faculty_students/<int:faculty_id>/', faculty_students, name='faculty_students'),
                  path('parsing/<int:faculty_id>/', Parsing, name='parsing'),
                  path('Report/<int:faculty_id>/', Report, name='Report'),
                  path('Work/<int:faculty_id>/<slug:students_id>/', Working, name='Work'),
                  path('logout/', logoutUser, name='logout'),
                  path('download', download_file, name='download'),
                  path('transfer/<int:faculty_id>/', transfer, name='transfer'),
                  path('graph/<int:faculty_id>/', graph, name='graph'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Loging/faculty/models.py
from django.db import models
from django.urls import reverse
from authorization.models import LoginFaculty

# from students.models import ThemeStudents


class FacultyUniversity(models.Model):
    NameFaculty = models.CharField(max_length=255, verbose_name='Название кафедры')
    FacultyLoginPasswords = models.ForeignKey(LoginFaculty, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.NameFaculty)

    def get_absolute_url(self):
        return reverse('faculty_index', kwargs={'faculty_id': self.id})


class Specialization(models.Model):
    Name_Specialization = models.CharField(max_length=250, verbose_name='Название специальности')
    Code_Specialization = models.CharField(max_length=250, verbose_name='Код специальности')
    SpecializationFaculty = models.ForeignKey(FacultyUniversity, on_delete=models.CASCADE,
                                              verbose_name='Специализация кафедры')


# class Discip(models.Model):
#     specialization = models.ForeignKey(GroupUniversity, on_delete=models.CASCADE)
#     Code = models.CharField()
#     Name = models.CharField()
#     Times = models.DateField(blank=True, null=True, verbose_name='Дата сдача')
#     chapter = models.CharField()
#
#     def __str__(self):
#         return self.Name

# class Supervisor(models.Model):
#     First_name = models.CharField(max_length=255, verbose_name='Имя преподователя')
#     Last_name = models.CharField(max_length=255, verbose_name='Фамилия преподователя')
#     Middle_name = models.CharField(max_length=255, verbose_name='Отчество преподователя')
#     FacultyGroup = models.ForeignKey(Specialization, on_delete=models.SET_NULL, null=True, verbose_name='Кафедра')
#
#     def __str__(self) -> str:
#         return str(f'{self.Last_name} {self.First_name[0]} {self.Middle_name[0]}')
#
#     class Meta:
#         verbose_name = 'Преподователь'
#         verbose_name_plural = 'Преподователь'
#         db_table = 'Преподователь'

Loging/faculty/forms.py
from django import forms
# from .models import Specialization


class AllDateStudent(forms.Form):
    OPTION_CHOICES = [
        ('AllDateStudent', 'Все данные'),
    ]
    allDateRadio = forms.ChoiceField(label='Вывод данных', choices=OPTION_CHOICES, widget=forms.RadioSelect(attrs={'name': 'AllDate'}))


class GroupDateStudent(forms.Form):
    OPTION_CHOICES = [
        ('GroupDateStudent', 'Данные по группе'),
    ]
    groupDateRadio = forms.ChoiceField(choices=OPTION_CHOICES, widget=forms.RadioSelect(attrs={'name': 'group'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['groupDateRadio'].widget.attrs.update({
            'class': 'group_find',
        })

class DateStudent(forms.Form):
    OPTION_CHOICES = [
        ('StudentDate', 'Данные по студенту'),
    ]
    studetnDateRadio = forms.ChoiceField(choices=OPTION_CHOICES, widget=forms.RadioSelect)


class AddFile(forms.Form):
    Files = forms.FileField(widget=forms.FileInput(attrs={'accept': '.xlsx, .docx'}))

Loging/faculty/views.py
import os
from django.conf import settings
from django.core.mail import send_mail
import datetime
import zipfile
from tempfile import TemporaryDirectory
from django.conf import settings
from docx import Document
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from Group.models import GroupUniversity, Discip
from .models import FacultyUniversity, Specialization
from .forms import GroupDateStudent, AddFile
from openpyxl import Workbook, load_workbook
from students.models import Students, Work
from django.http import HttpResponse


def today_work(faculty_id):
    faculty = FacultyUniversity.objects.get(FacultyLoginPasswords=faculty_id)
    specialization = Specialization.objects.filter(SpecializationFaculty=faculty)
    group = GroupUniversity.objects.filter(SpecializationGroup__in=specialization).order_by('NameGroup')
    date_now = datetime.date.today()

    try:
        for groups in group:
            date_times_course = Discip.objects.filter(groups=groups, types_work='Курсовая')
            date_times_practice = Discip.objects.filter(groups=groups, types_work='Практика')
            students = Students.objects.filter(GroupStudents=groups)

            for student in students:
                send_course_mail = False
                send_practice_mail = False
                course_message = ""
                practice_message = ""

                for date_time_cr in date_times_course:
                    result_date_course = (date_time_cr.Times_files - date_now).days
                    if not result_date_course < 0 and result_date_course != 0:
                        if result_date_course <= 6 and not Work.objects.filter(DiscipId=date_time_cr, StudentId=student,
                                                                               Type='Курсовая').exists():
                            send_course_mail = True
                            course_message += f" по предмету: {date_time_cr.Name}, осталось {result_date_course} дней до сдачи курсовой."

                for date_time_pr in date_times_practice:
                    result_date_practice = (date_time_pr.Times_files - date_now).days
                    if not result_date_practice < 0 and result_date_practice != 0:
                        if result_date_practice <= 6 and not Work.objects.filter(DiscipId=date_time_pr,
                                                                                 StudentId=student,
                                                                                 Type='Практика').exists():
                            send_practice_mail = True
                            practice_message += f" и что осталось {result_date_practice} дней до сдачи практики."

                if send_course_mail:
                    send_mail(
                        f'Напоминание о сдаче курсовой работы',
                        f'Добрый день {student.Last_name} {student.First_name} {student.Middle_name}.'
                        f' студент группы: {groups.NameGroup} напоминаем вам о предстоящей сдачи курсовой {course_message}',
                        settings.EMAIL_HOST_USER,
                        [student.EmailStudents]
                    )

                if send_practice_mail:
                    send_mail(
                        f'Напоминание о сдаче практики',
                        f'Добрый день {student.Last_name} {student.First_name} {student.Middle_name}.'
                        f' студент группы: {groups.NameGroup} напоминаем вам о предстоящей сдачи практики {practice_message}',
                        settings.EMAIL_HOST_USER,
                        [student.EmailStudents]
                    )

    except Exception as ex:
        return str(ex)


def faculty_index(request, faculty_id):
    today_work(faculty_id)
    faculty = FacultyUniversity.objects.get(FacultyLoginPasswords=faculty_id)
    specialization = Specialization.objects.filter(SpecializationFaculty=faculty)
    group = GroupUniversity.objects.filter(SpecializationGroup__in=specialization).order_by('NameGroup')
    students = Students.objects.filter(GroupStudents__in=group).order_by('GroupStudents', 'Last_name')
    if request.method == "POST":
        st = request.POST.get('student_work')
        # group_students = request.POST.get('groupStudents')
        group_date = request.POST.get('select')
        student_find = request.POST.get('student_fullname')
        data_all = request.POST.get('get_data')
        if group_date:
            students = Students.objects.filter(GroupStudents__NameGroup=group_date).order_by(
                'GroupStudents',
                'Last_name')
        elif student_find:
            students = Students.objects.filter(Last_name=student_find)
        elif data_all:
            students = Students.objects.filter(GroupStudents__in=group).order_by(
                'GroupStudents', 'Last_name')
        elif st:
            return redirect(reverse('faculty:Work', kwargs={'faculty_id': faculty_id,
                                                            'students_id': st}))

    group_date = GroupDateStudent()
    data = {
        'faculty_id': faculty_id,
        'id': faculty,
        'files': AddFile,
        'group': group,
        'student': students,
        'groups': group_date,
    }
    return render(request, 'faculty/index.html', context=data)


def graph(request, faculty_id):
    faculty = FacultyUniversity.objects.get(FacultyLoginPasswords=faculty_id)
    specialization = Specialization.objects.filter(SpecializationFaculty=faculty)
    group = GroupUniversity.objects.filter(SpecializationGroup__in=specialization).order_by('NameGroup')
    date_times = Discip.objects.filter(groups__in=group).order_by('groups')

    if request.method == 'POST':
        for key, value in request.POST.items():
            if key.startswith('group_'):
                group_id = key.split('_')[0]
                group_name = value
                courses = Discip.objects.filter(groups__NameGroup=group_name, types_work='Курсовая')
                practices = Discip.objects.filter(groups__NameGroup=group_name, types_work='Практика')
            if key.startswith('dateCourse_'):
                date_id = key.split('_')[0]
                date_course = value
            if key.startswith('datePractice_'):
                date_id = key.split('_')[0]
                date_practice = value
                for cours in courses:
                    if cours.Times_files != date_course and date_course != '':
                        course = Discip.objects.filter(groups__NameGroup=group_name, types_work='Курсовая').update(
                            Times_files=date_course)
                    elif cours.Times_files == date_course and date_course == '':
                        continue
                for pract in practices:
                    if pract.Times_files != date_practice and date_practice != '':
                        practice = Discip.objects.filter(groups__NameGroup=group_name, types_work='Практика').update(
                            Times_files=date_practice)
                    elif pract.Times_files == date_practice and date_practice == '':
                        continue

        return redirect(reverse('faculty:graph', kwargs={'faculty_id': faculty_id}))

    grouped_times = {}
    for date_time in date_times:
        group_name = date_time.groups.NameGroup
        if group_name not in grouped_times:
            grouped_times[group_name] = {'Курсовая': None, 'Практика': None}
        if date_time.types_work == 'Курсовая':
            grouped_times[group_name]['Курсовая'] = date_time.Times_files
        elif date_time.types_work == 'Практика':
            grouped_times[group_name]['Практика'] = date_time.Times_files

    data = {
        'faculty_id': faculty_id,
        'groups': group,
        'grouped_times': grouped_times
    }

    return render(request, 'faculty/graph.html', context=data)


def logoutUser(request):
    # logout(request)
    pass


def download_file(request):
    if request.method == "POST":
        download = request.POST.get('download')

        if not download:
            raise Http404("No file specified for download.")

        file_extension = os.path.splitext(download)[1].lower()
        content_type = 'application/octet-stream'  # Default content type

        if file_extension == '.zip':
            content_type = 'application/zip'
        elif file_extension == '.rar':
            content_type = 'application/x-rar-compressed'

        file_path = os.path.join(settings.MEDIA_ROOT, download)

        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type=content_type)
                response['Content-Disposition'] = f'attachment; filename="{os.path.basename(file_path)}"'
                return response
        else:
            raise Http404("File does not exist.")

    raise Http404("Invalid request method.")


def Working(request, faculty_id, students_id):
    students = Students.objects.filter(pk=students_id)
    faculty = FacultyUniversity.objects.get(FacultyLoginPasswords=faculty_id)
    specialization = Specialization.objects.filter(SpecializationFaculty=faculty)
    if Work.objects.filter(StudentId=students_id).exists():
        themes = Work.objects.filter(StudentId=students_id)
    elif not Work.objects.filter(StudentId=students_id).exists():
        themes = Work.objects.filter(StudentId=students_id)

    data = {
        'faculty_id': faculty_id,
        'students': students,
        'themes': themes,

    }
    return render(request, 'faculty/Student_work.html', context=data)


def Parsing(request, faculty_id):
    if request.method == "POST":
        files = AddFile(request.POST, request.FILES)
        if files.is_valid():
            uploaded_file = request.FILES['Files']
            file_name = uploaded_file.name

Loging/faculty/templates/faculty/Student_work.html
{% extends 'faculty/layout.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/faculty_menu.css' %}">
<link rel="stylesheet" href="{% static 'css/transfer.css' %}">
<link rel="stylesheet" href="{% static 'css/input_style.css' %}">
{% endblock %}

{% block menu %}
<div class="navbar">
    <a href="{% url 'faculty:faculty_index' faculty_id %}">Главная</a>

    <div class="dropdown">
        <button class="dropbtn"> {{ name_faculty.NameFaculty }}
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <a href="{% url 'faculty:logout' %}">Выйти</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
{% for students in students %}
<h1>{{ students.Last_name }} {{ students.First_name }} {{ students.Middle_name }} {{ students.GroupStudents }}</h1>
{% endfor %}
<table>
    <thead>
    <tr>
        <th>
            Курс
        </th>
        <th>
            Название работы
        </th>
        <th>
            Тип работа
        </th>
        <th>
            Работа
        </th>
        <th>
            Статус
        </th>
        <!--        <th>-->
        <!--            Консультант-->
        <!--        </th>-->
    </tr>
    </thead>
    <tbody>{% for themes in themes %}
    {% if themes.Files != None %}
    <tr>
        <td>
            {{ themes.Course }} курс
        </td>
        <td>
            {{ themes.Name_themes }}
        </td>
        <td>
            {{ themes.Types_work }}
        </td>
        <td>
            <form action="{% url 'faculty:download' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                <button type="submit" name="download" value="{{ themes.Files }}">{{ themes.Files }}</button>
            </form>
        </td>
        <td>
            {% if themes.statuc == True %}
            Сдано
            {% elif themes.statuc == False %}
            Не сдано
            {% endif %}
        </td>
    </tr>
    {% elif themes.Files == None %}
    <tr>
        <td>
             {{ themes.Course }} курс
        </td>
        <td>
            {{ themes.Name_themes }}
        </td>
        <td>
            {{ themes.Types_work }}
        </td>
        <td>
            <form action="{% url 'faculty:download' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                <button type="submit" name="download" value="{{ themes.Files }}">{{ themes.Files }}</button>
            </form>
        </td>
        <td>
            {% if themes.statuc == True %}
            Сдано
            {% elif themes.statuc == False %}
            Не сдано
            {% endif %}
        </td>
    </tr>
    {% endif %}

    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block script %}
{% endblock %}

Loging/faculty/templates/faculty/archive.html
{% extends 'faculty/layout.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/faculty_menu.css' %}">
<link rel="stylesheet" href="{% static 'css/input_style.css' %}">
{% endblock %}

{% block menu %}
<div class="navbar">
    <a href="{% url 'faculty:faculty_index' faculty_id %}">Главная</a>
    <div class="dropdown">
        <button class="dropbtn"> {{ name_faculty.NameFaculty }}
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <a href="{% url 'faculty:logout' %}">Выйти</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<label for="archive_group">Выгрузка по группе</label>
<form action="{% url 'faculty:archive' faculty_id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <select class="groupBtn" name="select" id="archive_group">
        {% for group in groups %}
        <option>
            {{ group.NameGroup }}
        </option>
        {% endfor %}
    </select>
<!--    <input type="radio" name="course" value="2">1 Курс-->
<!--    <input type="radio" name="course" value="4">2 Курс-->
<!--    <input type="radio" name="course" value="6">3 Курс-->
<!--    <input type="radio" name="course" value="8">4 Курс-->
<!--    <br>-->
    <button type="submit">Отправить</button>
</form>
<label for="student_fullname">По студенту</label>
<form action="{% url 'faculty:archive' faculty_id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <input type="text" class="find_student" name="student_fullname" id="student_fullname"><br>
    <button type="submit">Отправить</button>
</form>
{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'JS/addModalFile.js' %}"></script>
<script src="{% static 'JS/database.js' %}"></script>
<script src="{% static 'JS/content.js' %}"></script>
{% endblock %}

Loging/faculty/templates/faculty/index.html
{% extends 'faculty/layout.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/faculty_menu.css' %}">
<link rel="stylesheet" href="{% static 'css/faculty_btn.css' %}">
<link rel="stylesheet" href="{% static 'css/faculty_modal.css' %}">
<link rel="stylesheet" href="{% static 'css/faculty_content.css' %}">
<link rel="stylesheet" href="{% static 'css/input_style.css' %}">
{% endblock %}

{% block menu %}
<div class="navbar">
    <a href="{% url 'faculty:graph' faculty_id %}">График</a>
    <a href="{% url 'faculty:transfer' faculty_id %}">Перевод</a>
    <a href="{% url 'faculty:faculty_students' faculty_id %}">Студенты</a>

    <div class="dropdown">
        <button class="dropbtn"> {{ id.NameFaculty }}
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <a href="{% url 'faculty:logout'  %}">Выйти</a>
        </div>
    </div>
</div>
{% endblock %}

{% block btn %}
<div id="modal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Добавить файл</h2>
        <form action="{% url 'faculty:parsing' faculty_id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ files.Files }}
            <button type="submit">Загрузить</button>
        </form>
    </div>
</div>

<!-- Модальное окно для отчета -->
<div id="reportModal" class="modal">
    <div class="modal-content">
        <span class="close" id="reportModalClose">&times;</span>
        <h2>Отчет</h2>
        <form action="{% url 'faculty:Report' faculty_id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <select class="groupBtn" name="select" id="report_group">
                {% for group in group %}
                <option>
                    {{ group.NameGroup }}
                </option>
                {% endfor %}
            </select>
            <button type="submit">Отправить</button>
        </form>
    </div>
</div>

<!-- Модальное окно для архивов -->
<div id="archiveModal" class="modal">
    <div class="modal-content">
        <span class="close" id="archiveModalClose">&times;</span>
        <h2>Архивы</h2>
        <label for="archive_group">Выгрузка по группе</label>
        <form action="{% url 'faculty:archive' faculty_id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <select class="groupBtn" name="select" id="archive_group">
                {% for group in group %}
                <option>
                    {{ group.NameGroup }}
                </option>
                {% endfor %}
            </select>
            <button type="submit">Отправить</button>
        </form>
        <label for="student_fullname">По студенту</label>
        <form action="{% url 'faculty:archive' faculty_id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <input type="text" class="find_student" name="student_fullname" id="student_fullname"><br>
            <button type="submit">Отправить</button>
        </form>
    </div>
</div>

<div class="btn_positon">
    <button class="btn_left" id="ModalReport">Отчёт</button>
    <button class="btn_left" id="ModalArchive">Архивы</button>
    <button class="btn_left" id="openModal">Добавить</button>
    <!--    <button class="btn_right" id="editButton">Изменить</button>-->
</div>
{% endblock %}

{% block content %}
<div class="content">
    <h5>Вывести данные: </h5>
    <input type="radio" class="form-check-input" name="data_type" id="all_date_id" value="all" checked> <label
        for="all_date_id">Все данные</label>
    <input type="radio" class="form-check-input" name="data_type" id="groups_id" value="group"> <label for="groups_id">Данные
    по группе</label>
    <input type="radio" class="form-check-input" name="data_type" id="student_id" value="student"> <label
        for="student_id">Данные по студенту</label>
</div>

<div class="all_date_student" style="display: none;">
    <form action="{{ id.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <button type="submit" name="get_data">Вывести все данные</button>
    </form>
</div>

<div class="group_select" style="display: none;">
    <form action="{{ id.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <select class="groupBtn" name="select">{% for group in group %}
            <option>{{ group.NameGroup }}</option>
            {% endfor %}</select>
        <button type="submit" name="get_data">Вывести данные</button>
    </form>
</div>

<div class="student_input" style="display: none;">
    <form action="{{ id.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <input type="text" class="find_student" name="student_fullname"><br>
        <button type="submit" name="get_data">Вывести данные</button>
    </form>
</div>

{% for st in course %}
<input value="{{ st.Name_themes }}" size="35">
<input value="{{ st.Students_Themes }}" size="35">
<input type="text" value="{{ st.get_Status_themes_display }}">
<button name="files" value="{{ st.Course }}">{{ st.Course }}</button><br>
{% endfor %}

<div class="container-fluid ">
    <form action="{{ id.get_absolut_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <div class="position_left text-field ">
                <div class="scroll-table">
                    <table>
                        <thead>
                        <tr>
                            <th class="Group">Группа</th>
                            <th class="Full_name">ФИО</th>
                            <th class="Themes">Статус</th>
                            <th class="Work">Работы</th>
                        </tr>
                        </thead>
                    </table>
                </div>
                <div class="scroll-table-body">
                    <table>
                        <tbody>
                        {% for student in student %}
                        <tr>
                            <td><input type="text" name="groupStudents"
                                       class="text-field__input student-{{ student.id }}"
                                       value="{{ student.GroupStudents }}"
                                       size="43"
                            ></td>
                            <td><input type="text" name="full_name"
                                       class="text-field__input student-{{ student.id }}"
                                       disabled
                                       size="44"
                                       value="{{ student.Last_name }} {{ student.First_name }} {{ student.Middle_name }}">
                            </td>
                            <td>
                                <input type="text"
                                       class="text-field__input student-{{ student.id }}"
                                       disabled
                                       size="44"
                                       value="{{ student.get_Status_Students_display }}">
                            </td>
                            <td>
                                <form action="{{ id.get_absolut_url }}" method="post" enctype="multipart/form-data">
                                    {%csrf_token%}
                                    <button type="submit" class="button-style_font"
                                            name="student_work" value="{{ student.id }}">Работы
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!--        <button type="submit" id="saveButton" style="display: none;">Сохранить</button>-->
    </form>
</div>

<div id="openModalReport" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Название</h3>
                <a href="#close" id="close" title="Close" class="close">×</a>
            </div>
            <div class="modal-body">
                <p>Содержимое модального окна...</p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'JS/addModalFile.js' %}"></script>
<script src="{% static 'JS/database.js' %}"></script>
<script src="{% static 'JS/content.js' %}"></script>

{% endblock %}

Loging/faculty/templates/faculty/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block style %}{% endblock %}
    <title>Document</title>
</head>
<body>
{% block menu %}
{% endblock %}

{% block btn %}
{% endblock %}

{% block content %}
{% endblock %}

{% block script %}
{% endblock %}

</body>
</html>